version: '3'

networks:
  traefik-net:
    external: true

services:
  # Laravel Application
  php-app:
    build:
      context: ./project
      dockerfile: DockerfileNginx  # Specify the name of your Dockerfile if it's not named 'Dockerfile'
    container_name: ${CONTAINER_PREFIX}-app
    working_dir: /var/www/html
    volumes:
      - ${CODE_PATH}:/var/www/html
    networks:
      - traefik-net
  # php-app-apache:
  #   build:
  #     context: ./project
  #     dockerfile: DockerfileApache  # Specify the name of your Dockerfile if it's not named 'Dockerfile'
  #   container_name: ${CONTAINER_PREFIX}-app
  #   working_dir: /var/www/html
  #   volumes:
  #     - ${CODE_PATH}:/var/www/html
  #   networks:
  #     - traefik-net
  #   labels:
  #     - "traefik.http.routers.${APP_NAME}-${CONTAINER_PREFIX}.rule=Host(`${APP_NAME}-${CONTAINER_PREFIX}.${HOST_PREFIX}`)"
  # Nginx
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_PREFIX}-nginx
    ports:
      - "8001:8001"
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf
      - ${CODE_PATH}:/var/www/html
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.nginx.rule=Host(`${APP_NAME}-${CONTAINER_PREFIX}.${HOST_PREFIX}`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=8001"

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_PREFIX}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - traefik-net
    labels:
      - "traefik.enable=false"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis Server
  redis:
    image: redis:alpine
    container_name: ${CONTAINER_PREFIX}-redis
    networks:
      - traefik-net
    labels:
      - "traefik.enable=false"
    volumes:
      - redis_data:/data

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_PREFIX}-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1234:80"
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin-${CONTAINER_PREFIX}.${HOST_PREFIX}`)"
    volumes:
      - phpmyadmin_data:/data

  # MeiliSearch
  meliserach:
    image: getmeili/meilisearch:v1.6
    container_name: meliserach
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data:/data.ms  # Mount volume for MeiliSearch data persistence
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.meliserach.rule=Host(`meilisearch-${CONTAINER_PREFIX}.${HOST_PREFIX}`)"

volumes:
  phpmyadmin_data:
  redis_data:
  mysql_data:
  meili_data:
