version: '3'

networks:
  traefik-net:
    external: true

services:
  # Laravel Application
  app:
    build:
      context: ./project
      dockerfile: Dockerfile  # Specify the name of your Dockerfile if it's not named 'Dockerfile'
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./project/${CODE_PATH}:/var/www/html
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.laravel-app.rule=Host(`laravel-app.localhost`)"

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
      - traefik-net
    labels:
      - "traefik.enable=false"

  # Redis Server
  redis:
    image: redis:alpine
    container_name: laravel-redis
    networks:
      - traefik-net
    labels:
      - "traefik.enable=false"

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "1234:80"
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
